### ISSUE TITLE
hi doctor Bho Matthiesen

### ISSUE THREAD

**Issue by ken0225** [bmatthiesen/IRS-continuous#1]
hi doctor Bho Matthiesen, I made a collection that contains some codes for RIS(IRS) papers, I hope it is ok for you to include this repertory. 

The link is https://github.com/ken0225/RIS_Codes_Collection

thanks and best regards

ken

**Comment by bmatthiesen** [comment]
Sure, thanks for including this code in your list.

Best,
Bho

**Comment by Nambundo** [comment]
hello you can help me ?
